sudo: required
services:
  - docker
before_install:
  - sudo service docker restart ; sleep 10
install:
  - docker build -t jdubois/jhipster-docker .
  - docker run -d -p 9090:9090 -p 3000:3000 -p 3001:3001 -w /home/jhipster/jhipster-sample-app/ --name=jhipster jdubois/jhipster-docker mvn spring-boot:run ; sleep 360
script:
  - docker logs jhipster
  - curl --retry 10 --retry-delay 5 -I http://localhost:9090/ | grep "HTTP/1.1 200 OK"
